app:
  image: rheosystems/hydra:latest
  ports:
    - "3000:3000"
  environment:
    - HYDRA_DBI="dbi:Pg:dbname=hydra;host=rheosystems-main.cstivet9jtpa.eu-central-1.rds.amazonaws.com;user=hydra;"
    - HYDRA_DATA="/var/lib/hydra"
  volumes:
    - /data/hydra:/var/lib/hydra
  restart: always
